### PR TITLE
Bugfix/handle empty options

### LINKED ISSUE #44: Please don't set the label to opts.name
[Line 38](https://github.com/AmpersandJS/ampersand-select-view/blob/master/ampersand-select-view.js#L38):
``` javascript
this.label = opts.label || this.name; // init as string. render() mutates into DOM el with .textContent equal to this value
```

The way I'm using the select-view, when I deliberately set the label to nothing that means I _don't_ want a label to appear. Additionally, the `name` I pass into the select-view options usually matches the model attribute and is rarely (if ever) a human friendly string.

If it has to be a string, then at least set it to one. I know an empty string returns `false`, but I didn't see any further check, and this way it would at least avoid unintended side effects of setting it to the `name`.

``` javascript
this.label = opts.label || ""; 
```

### PR DESCRIPTION
**Pull request by cdaringe**
Closes #44

### CODE REVIEW

**Comment by wraithgar** [comment]
+1

**Comment by fyockm** [comment]
Aside from my personal preference toward ternary, looks good. +1 from me. Would love to see this released soon!

**Comment by cdaringe** [comment]
@fyockm @wraithgar
is the combo of your two +1s OK to close, or are we sticking to core_team +1 && module-at-hand-maintainer +1s only?  i searched around and couldnt find it.  i know it was discussed it *somewhere*

**Comment by wraithgar** [comment]
@cdaringe +1 from core OR leads http://ampersandjs.com/learn/bug-triage-process

In my humble opinion :shipit:

As far as ternary goes, in the age of minification we try to lean on the side of longhand for if statements.

**Comment by cdaringe** [comment]
@wraithgar, drats, i knew [it was somewhere](http://ampersandjs.com/learn/bug-triage-process#pull-requests)!  just to be clear, i interpret your remark above as stating that  (gar + 1) && (fyockm + 1) === sufficient to merge.  however, i interpret your link above to exclude fyockm's +1, as he isnt *this module's* lead.  set me straight!

**Comment by wraithgar** [comment]
I was following the spirit vs the letter of the law on that given that @fyockm is *a* lead in another ampersand module.  Probably should let someone else besides me weigh in.  @AmpersandJS/core-team can we get a +1 and/or some discussion about the triage process now that we have many more leads?

**Comment by HenrikJoreteg** [comment]
I see three competent people with vested interest in the project all wanting these changes, I've never been one for strict rules. I'd say ship it, especially in these cases where there's little to no opposition.

**Comment by cdaringe** [comment]
and that's why I like workin' with you guys :+1:

**Pull request merged**
