### PR TITLE
Refactoring to be extended from ampersand-view.

### PR DESCRIPTION
**Pull request by tamasdancsi**
I bumped into this issue and think it's might be helpful for you.
"ampersand-select-view does not extend ampersand-view" (https://github.com/AmpersandJS/ampersand-select-view/issues/2)

### CODE REVIEW

**Comment by e2jk** [comment]
Any update on this PR? It would be great to be able to `.extend()` just like we do with `ampersand-input-view`.

**Comment by kamilogorek** [comment]
@tamasdancsi sorry it took so long. Could you please rebase this commit so we can get it reviewed?

**Comment by cdaringe** [comment]
This looked good.  Unfortunately, after pulling the PR branch locally, the diff is pretty unwieldy.  It's probably easier and safer to manually replay the updates line by line from the *latest* state, unless someone has a better idea.  Because this refactor touches every function as it converts from the prototype def to obj def style, the likelihood of a repeat situation is very likely unless other PRs are either (a) minimal or (b) frozen until this one gets through.  @tamasdancsi, do you still intend to actively work on this?

**Comment by wraithgar** [comment]
We may want to just take another run at this post-3.0.0

**Comment by cdaringe** [comment]
agreed.  shall we close this PR for the time being?

**Pull request closed without merging**
