### PR TITLE
Closes #47

### LINKED ISSUE #47: Validation error message not showing on parent form submit
I am using an ampersand-select-view within an ampersand-form-view like this:
```javascript
new FormView({
  ...
  fields: [
    ...
    new SelectView({
      el: self.queryByHook('category'),
      name: 'category',
      options: categoryOptions,
      label: 'Main Category *',
      required: true,
      requiredMessage: "Please select a category."
    })
  ]
});
```
The select-view renders correctly. It is also considered in the form view's validation - selecting no option does prevent the submit. However, the error message is not displayed upon submit. The error is shown, though, if I select an entry and then deselect it again. 

I use other ampersand-input-views in the same FormView, which work fine.

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement
empty unselectedText not honored, and selects first options from options list instead

### CODE REVIEW

**Comment by cdaringe** [comment]
**bump**. requesting reviews

**Comment by wraithgar** [comment]
Yes thanks. +1 visual

**Comment by lukekarrys** [comment]
+1

**Comment by fyockm** [comment]
I know you already got the 2 +1's, but I'll throw another :+1: into the mix.

**Comment by cdaringe** [comment]
nice :smile: tests are passing, but zuul issue is 'still a thing', hence the build failing. publishing as patch

**Pull request merged**
