### PR TITLE
Hide label when opts.label is not set (fixes: #53)

### PR DESCRIPTION
**Pull request by e2jk**

### CODE REVIEW

**Comment by cdaringe** [comment]
This request removes the default configuration of a field label fallback.  I know that its presence has caused some grief, and that's the last thing we want, but certainly some users use the fallback and are content with it.  Would not simply setting `label: null` not fix your issue?  the node would still be present, but empty, and _likely_ not impacting the rendering of the DOM unless there was some wily nily CSS at play.

thoughts?

**Comment by cdaringe** [comment]
meh, ok, in favor of matching input view's behavior, i'm in support of it, however it will be a major bump.

+1 once test are confirmed passing

**Comment by cdaringe** [comment]
@e2jk, will you pull the latest upstream master into your branch?  hopefully that resolves the testing issues :)

**Comment by wraithgar** [comment]
+1 yeah this will be a major.  Could a test be added for this?

**Comment by wraithgar** [comment]
@e2jk I made this PR w/ tests updated and it looks like there's still a bug here. The label ends up being the string `'undefined`' somehow.  Will need to get that test passing before we can merge (either in this PR or in the other one, doesn't matter. Once one works we'll merge and close the other)

**Comment by wraithgar** [comment]
Found it! Closing this in favor of the other PR which has your work in it already @e2jk plus the tweak to get tests passing. Thanks for pushing for this change it feels like the right one, all told.

**Comment by e2jk** [comment]
Great!

**Pull request closed without merging**
