### PR TITLE
Try zuul for saucelabs

### PR DESCRIPTION
**Pull request by latentflip**

### CODE REVIEW

**Comment by bear** [comment]
Any reason to not merge this?

**Comment by latentflip** [comment]
Hmm, yes, I think I still need to figure out how to run the tests locally when running locally, rather than it running them on saucelabs on every commit.

**Comment by bear** [comment]
any reason to not have a test running script that decides based on it being a local test run, and if so use tape?

**Comment by latentflip** [comment]
Done, by adding a test-ci run script, and having travis use that. I think this is good to go now then.

**Pull request merged**
