### PR TITLE
ADDED: Don't validate until the select is either blurred, or the user tr...

### PR DESCRIPTION
**Pull request by erd0s**
...ies to submit the form

### CODE REVIEW

**Comment by kamilogorek** [comment]
It'd prevent instant user feedback which may not be desired behavior for everyone.
If we however decide to keep it, please detach handler on line 175.

**Comment by erd0s** [comment]
Done!

Just curious about a situation where you'd want it to report on the validation before blur/submit? I just followed the method they use in the InputView module, I was thinking you'd probably want all fields to be validated at the same time.

**Comment by lukekarrys** [comment]
I do think this should be the default behavior (like it is in InputView). I think this is the right way to do it. Maybe @wraithgar has input here?

If we do decide to land this, I think it should come with a test. It'd be nice so that we can prevent any regressions in the future.

**Comment by erd0s** [comment]
Okie dokie, I've got a few things I gotta finish today then I'll look at a test

**Comment by cdaringe** [comment]
@kamilogorek @lukekarrys, reviewing this I saw again that we bind a `change` listener to `this.el`.  Unless this was intentional, I'm thinking we should really bind directly to`this.select`.  Otherwise, we're reacting to all sorts of other activity, such as a `className` change on the label span, for instance.  Any change activity that doesn't correlate directly to the select-view's value shouldn't be triggering select change handlers.

**Comment by kamilogorek** [comment]
@cdaringe "fair point you have there."

**Comment by wraithgar** [comment]
Between @cdaringe's excellent point, and this issue (https://github.com/AmpersandJS/ampersand-select-view/issues/11) maybe it's worth discussion what exactly we are 'listening' for. I agree that the onChange should reflect changes to the select input's events.  Additionally, our view's state also should be considered something that can be evented (valid, current value, rendered)

**Comment by nickryall** [comment]
Hi Guys. I was just wondering if the fix for #23 ( #32 ) resolves this issue, or is there another case that this PR covers? 

I think validation *should* be triggered on initialization if a starting `value` is passed. Think of a case where there is a pre-populated form and you want to highlight the fields as `valid`. 

I've added some additional tests over at #32 to convey what I think is the desired behaviour for each case.

Happy with either solution, just wanting to prevent any duplication or conflicts :)

**Comment by cdaringe** [comment]
@nickryall, I tend to agree with @erd0s on this one.  i dont think that the form should shout at the user on opening.  it will be validated soon enough.  however, in alignment with your intent, I do think it's important to protect your data.  As such, with my [3.0.0 proposal](https://github.com/AmpersandJS/ampersand-select-view/pull/34) (thanks for the review by the way), rather than *validate* on construction, simply don't accept invalid options--period.  setting an invalid option is an application design error, so error out!

@wraithgar, on "what are we listening for".  My thought process begins with "what's the purpose of this field-view"?  It's to produce a quality, validated value from the select control, per the designer's intent.  Therefore, I would suggest that we listen for any activity within our micro-DOM that impacts that `value`.  All other activity within the module orbits around it.  Thoughts?

**Comment by nickryall** [comment]
@cdaringe  With #32,  the  invalid/error message will only be displayed on initialization if an *invalid* starting `value` is passed. With #34 included, the error/invalid message will never be displayed on initialization - period -  which is great ;)

So, I think the only case this PR will then resolve is the prevention of setting `validClass` on `el`, if a *valid* `value` is passed on initialization.  

Most of the time this is what would be desired as you would want to just pre-select an option.  However, I think there may be some cases where this is the desired behaviour. e.g.  If you were specifying a starting value for the field, you would likely be pre-populating a form for the user and may want to highlight the already valid fields.  Or... maybe this is too edge case to worry about ;)

**Comment by cdaringe** [comment]
@nickryall, agreed.  I don't feel like its *common* to visit a form and see positive affirmations immediately, but there certainly could be use cases.  Sounds like you might have some :).  With this said, why don't we propose to:

1. not validate by default
1. add an option to `eagerValidate` (or equivalent), and denote in the README that it would trigger the validation classes

**Comment by nickryall** [comment]
@cdaringe Nice. To kee things simple, I'll look at adding an `eagerValidate` option as a separate PR, once all the outstanding PR's are resolved.

**Comment by cdaringe** [comment]
@nickryall, I added `eagerValidate` to my latest 3.0.0 PR.  It mashes with a tiny bit with your great updates, so I'd plan on getting your stuff merged first, before requesting the community to look at mine.
@erd0s, see [this line in your code](https://github.com/AmpersandJS/ampersand-select-view/pull/24/files#diff-cd18a4507088002c17b5ed65ce48e6c1R204) .  If the field doesn't validate immediately, `this.valid` doesn't get set, and the parent FormView won't know if the field is valid or not.  the intent is not to show the messages, vs. determine the validity.  thus, see what I did [here in my PR](https://github.com/AmpersandJS/ampersand-select-view/pull/36/files#diff-cd18a4507088002c17b5ed65ce48e6c1R212).  `skipValidate` should really be `skipValidationMessages` or equivalent

**Comment by cdaringe** [comment]
hi @erd0s, apologies for the huge dialog on this one!

1. the extra validation & functions that you added here was already added by @nickryall in subsequent commits (minus handleBlur)
1. in our other fieldView READMEs (ref input view), we don't blur explicitly

> Will not show error messages pre-submit, or if it's never had a valid value. This lets people tab-through a form without triggering a bunch of error messages.

I hold the counter-opinion to @lukekarrys--I think consistency is important for the user experience across controls, specifically because of the tabbing.

in light of PR #43 4.0.0 RC (which has high precedence given issue #42), I'd like to put this review on hold, or perhaps close it temporarily until the the above is merged and conflicts resolved.  Let me know your thoughts.  thanks!

**Comment by cdaringe** [comment]
hi @erd0s, closing per the above remark, for now.  let's reopen to discuss further as needed

**Pull request closed without merging**
