### PR TITLE
Fix for https://github.com/AmpersandJS/ampersand-select-view/issues/23

### LINKED ISSUE #23: should not flag as invalid on initialization
If I instantiate a new select-view with `required: true` and `unselectedText` defined, I get a `selection required` message when the form first loads.

### PR DESCRIPTION
**Pull request by nickryall**
This is a fix for #23 

This basically skips calling setValue ( which then triggers the validate method ) if unselectedText is specified and there is no initial value passed in.  It also ensures the error message is not displayed.

I realise there are currently some related issues and solutions being discussed (i.e. #22 ) , so please feel free to ignore this PR if it doesn't fit into the overall plan.

### CODE REVIEW

**Comment by wraithgar** [comment]
Pinging @bear to see if the test failure is a fluke or something that can be addressed?

**Comment by bear** [comment]
I'll take a look at this now

**Comment by bear** [comment]
I added the zuul saucelab info to the travis.yml file - you may need to update your PR to include the latest version of travis.yml

**Comment by nickryall** [comment]
Closing this. I realised there are a few more issues that make this hard to test consistently when used within a form-view. i.e.  There is no beforeSubmit method and the render does not return 'this'.  I'll look at submitting a new PR with these issues resolved also.

**Pull request closed without merging**
