### PR TITLE
Update ampersand-view to version 9

### PR DESCRIPTION
**Pull request by imorrison**
See the issue here: https://github.com/AmpersandJS/ampersand-select-view/issues/71

### CODE REVIEW

**Comment by wraithgar** [comment]
+1 tests pass locally for me

**Comment by cdaringe** [comment]
so many updates! :) thanks @imorrison! +1

**Comment by imorrison** [comment]
Awesome. Thanks for merging. When you push the changes to npm, I can also update ampersand-form-view (it has `ampersand-input-view` & `ampersand-checkbox-view` as `devDependencies`).

**Comment by wraithgar** [comment]
Great! looking forward to those PRs @imorrison 

@cdaringe these are major bumps since this is a major dependency update, right?  If you haven't published by tomorrow AM PST I'll do that.

**Comment by cdaringe** [comment]
i agree. yea, i will do all select/checkbox/input, and do changelog updates in each

**Comment by cdaringe** [comment]
all day, the registry has been having some serious issues.  perhaps in wake of yesterdays drama there's been a lot of patching?  regardless, publishing too many times, and i had to piece-by-piece our publish scripts to make her buck.  regardless, all is updated and per expectation.

+ ampersand-input-view@6.0.0
+ ampersand-checkbox-view@5.0.0
+ ampersand-select-view@7.0.0

**Comment by wraithgar** [comment]
Thanks for seeing those through to publishing

**Pull request merged**
