### PR TITLE
#75 allow unselected text option when using with collections

### PR DESCRIPTION
**Pull request by hsimah**
enhancement for issue #75. collection backed select views can have unselected option and text placeholder.

### CODE REVIEW

**Comment by dhritzkiv** [comment]
Thanks for the PR. Would you mind adding a test for this new functionality? I'll review it later this weekend.

**Comment by hsimah** [comment]
Jeez, you sound like my boss - always with the tests! I'll do that now.

**Comment by dhritzkiv** [comment]
Haha it's always good practice to add tests. By the way, don't worry if the tests don't pass here on Github: there's something wrong with our configuration on travis-ci.

Once you've added a test or two, I'll pull it down and check it locally.

**Comment by hsimah** [comment]
Mate, this is strange. When I went to do the tests it appears that your control already supported unselected text and collections. I must have had something wrong with my configuration because I swear it wasn't working last night!

**Comment by dhritzkiv** [comment]
Ah! No worries. If you do come across the issue again, feel free to open this PR again with your tests. :)

**Pull request closed without merging**
