### PR TITLE
Bind change event listener to select, not el.

### PR DESCRIPTION
**Pull request by hailwood**
Just a simple bug fix.

### CODE REVIEW

**Comment by hailwood** [comment]
That fail aint the codes fault.

> ampersand-select-view@4.3.2 test-ci /home/travis/build/AmpersandJS/ampersand-select-view
zuul -- test/index.js
Error:
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.

**Comment by cdaringe** [comment]
+1, tests pass locally

**Comment by kamilogorek** [comment]
:+1:

**Comment by cdaringe** [comment]
it's a simple patch, but is potentionally breaking.  will publish as major hopefully later today. @hailwood, mind patching the changelog in the readme @5.0.0?

**Comment by cdaringe** [comment]
published as 5.0.0

**Pull request merged**
