### PR TITLE
Add check for parent update method

### PR DESCRIPTION
**Pull request by bryanspears**
When used as a view/subview there isn't an update method by default as there is with a form view.

### CODE REVIEW

**Comment by cdaringe** [comment]
:+1:

**Comment by kamilogorek** [comment]
+1

**Comment by pgilad** [comment]
looks good. I was thinking of perhaps using `lodash.isfunction` for this. Thoughts?

**Comment by kamilogorek** [comment]
@pgilad I though the same, but the only thing `_.isFunction` is adding is basically Safari regexp bug. But I believe no one will ever assign regexp as their `update` function :P

**Comment by cdaringe** [comment]
tests passing

**Pull request merged**
